apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upvy-prometheus-k8s
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch"]
